name: Publish Docs
run-name: ${{ github.actor }} is deploying new changes to documentation
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."
      - name: Check out ${{ github.repository }} repository code
        uses: actions/checkout@v3
      - name: Build Docs Server
        run: |
          cd ${{ github.workspace }}/docs
          sudo sh serve.sh
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/_book/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Artifacts
        uses: actions/deploy-pages@v2
